name: AI Pull Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write  # Required for PR comment

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full commit history
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch base and head branches
      run: |
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
        git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}

    - name: Generate PR diff
      run: |
        git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > diff.txt

    - name: Run AI Review with OpenAI
      id: ai
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        DIFF_CONTENT=$(cat diff.txt | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

        RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-3.5-turbo",
            "messages": [
              {
                "role": "user",
                "content": "You are an experienced senior software engineer reviewing a Pull Request diff.
                   Your review should include:
                   1. Any bugs, logical issues, or missing validations
                   2. Security risks or framework misuse
                   3. Unused or repetitive code
                   4. Suggestions to improve performance or readability
                   5. Gaps in error handling or edge cases
                   6. Recommendations with before/after code where applicable
                   End with a summary of overall feedback. Here is the code diff::\n\n'"$DIFF_CONTENT"'"
              }
            ]
          }')

        REVIEW=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

        echo "REVIEW<<EOF" >> $GITHUB_OUTPUT
        echo "$REVIEW" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Comment on the PR with AI Review
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          🤖 **AI Code Review Feedback**
          
          ${{ steps.ai.outputs.REVIEW }}
