name: AI Pull Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get PR Diff
      run: |
        git fetch origin main
        git diff origin/main...HEAD > diff.txt

    - name: Run AI Review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        curl https://api.openai.com/v1/chat/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d @- <<EOF
        {
          "model": "gpt-3.5-turbo",
          "messages": [{
            "role": "user",
            "content": "Act as a senior software engineer. Review the following code diff:\n\n$(cat diff.txt)"
          }]
        }
EOF

